apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
spec:
  selector:
    matchLabels:
      app: mongo
  serviceName: mongo
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:8.0.3-noble
          imagePullPolicy: Always
          ports:
            - containerPort: 27017
              name: mongo
          env:
            {{- range .Values.env }}
            - name: {{ .identifier }}
              value: {{ .value | quote }}
            {{- end }}
          volumeMounts:
            - name: mongo-mount
              mountPath: /data/db
      volumes:
        - name: mongo-mount
          hostPath:
            path: {{ $.Values.storage.mongo.hostPath }}
